name: FAHResourceDonor
version: 1.0.0
main: com.thijs226.fahdonor.FAHResourceDonor
api-version: 1.21
author: Thijs226
description: Donate unused server CPU to Folding@home medical research
website: https://github.com/Thijs226/FAH-ResourceDonor

commands:
  fah:
    description: Manage Folding@home integration
    usage: /fah <status|stats|account|cause|vote|diseases|pause|resume|cores|web|reload>
    aliases: [folding, fahdonor]

permissions:
  fahdonor.admin:
    description: Full admin access to FAH Resource Donor
    default: op
    children:
      fahdonor.account: true
      fahdonor.cause: true
      fahdonor.pause: true
      fahdonor.cores: true
      fahdonor.reload: true
      fahdonor.web: true
      
  fahdonor.account:
    description: Manage F@H account settings
    default: op
    
  fahdonor.cause:
    description: Change research cause
    default: op
    
  fahdonor.stats:
    description: View contribution statistics
    default: true
    
  fahdonor.pause:
    description: Pause/resume folding
    default: op
    
  fahdonor.cores:
    description: Manually set core allocation
    default: op
    
  fahdonor.reload:
    description: Reload plugin configuration
    default: op
    
  fahdonor.web:
    description: Access web interface info
    default: op