name: FAHResourceDonor
version: ${version}
main: com.thijs226.fahresourcedonor.FAHResourceDonor
api-version: 1.21
author: Thijs226
description: A Minecraft plugin that donates server resources to Folding@Home research
website: https://github.com/Thijs226/FAH-ResourceDonor-plugin

commands:
  fah:
    description: Folding@Home ResourceDonor commands
    usage: /<command> [status|start|stop|reload|info|debug|stats]
    permission: fah.admin
    aliases: [folding, fahdonor]

permissions:
  fah.admin:
    description: Allows use of FAH admin commands
    default: op
  fah.view:
    description: Allows viewing FAH status
    default: true