# FAH Resource Donor Configuration
# By Thijs226 - Donate unused server resources to Folding@home

config-version: 2

# Legacy Configuration Support (for backward compatibility)
# These settings are supported for users upgrading from older versions
fah:
  # Your Folding@home token/passkey (legacy format)
  # Get your passkey at: https://apps.foldingathome.org/getpasskey
  token: ""
  
  # Team ID (legacy format)
  team: "1067089"
  
  # Donor name (legacy format)
  donor-name: "Thijs226_MCServer"
  
  # Status check interval in seconds (legacy format)
  check-interval: 300

folding-at-home:
  # Automatic Installation
  # Set to false if you want to install FAH manually
  auto-install: true
  
  # Port Configuration (IMPORTANT for hosted servers!)
  # Most Minecraft hosts only provide ONE port
  ports:
    # Control port for FAH communication (0 = disabled/no control)
    # Set to 0 for shared hosting (Apex, Shockbyte, etc.)
    # Set to 36330 for VPS/dedicated servers
    control-port: 0
    
    # Web interface port (0 = disabled)
    # Set to 0 for shared hosting
    # Set to 7396 for VPS/dedicated servers  
    web-port: 0
    
    # Run mode when ports are disabled
    # "file-based" = Restart FAH to change cores (works on all hosts)
    no-port-mode: "file-based"
  
  # IMPORTANT: Your Folding@home Account Details
  # You need EITHER username+team+passkey OR a token!
  account:
    # OPTION 1: Traditional Setup (Recommended)
    # =========================================
    # Your Folding@home username
    # Register at: https://foldingathome.org/start-folding/
    username: ""
    
    # Your team ID
    # Find teams at: https://stats.foldingathome.org/teams
    # Default: 0 (no team)
    team-id: "0"
    
    # Your passkey for bonus points (32 characters)
    # Get one at: https://apps.foldingathome.org/getpasskey
    # Example: "1234567890abcdef1234567890abcdef"
    passkey: ""
    
    # OPTION 2: Account Token (Alternative)
    # ======================================
    # Your account token to link this server to your F@H account
    # Get from your F@H account dashboard when logged in
    # This links the server as one of your machines
    # Note: Anyone with this token can link machines to your account!
    account-token: ""
    
    # Machine name (how this server appears in your account)
    machine-name: "Minecraft-Server"
    
    # Use anonymous mode (hides username from stats)
    anonymous: false
  
  # Research Cause Preference
  cause-preference:
    # Primary cause: ANY, ALZHEIMERS, CANCER, HUNTINGTONS, PARKINSONS, 
    #                INFLUENZA, DIABETES, COVID-19, HIGH_PRIORITY
    primary: "ANY"
    
    # Secondary cause (backup)
    secondary: "HIGH_PRIORITY"
    
    # Allow any cause if preferred unavailable
    allow-any-fallback: true
    
    # GPU folding preference (if available)
    gpu-cause: "HIGH_PRIORITY"
  
  # Default account settings (used if above is blank)
  # This is a fallback - PLEASE SET YOUR OWN ACCOUNT ABOVE!
  default-account:
    username: "Anonymous"
    team-id: "1067089"
    
  # Allow players to use their own accounts
  allow-player-accounts: true
  
  # Democratic cause voting
  democratic-cause:
    enabled: true
    vote-command: true
    auto-switch: true
    vote-period: 24  # hours
  
  # Web Control Interface
  web-control:
    enabled: true
    allowed-ips:
      - "127.0.0.1"
      - "192.168.1.0/24"
    password: ""

server:
  # Total CPU cores available
  # This will be automatically adjusted based on detected environment
  total-cores: 8
  
  # Cores to always reserve for Minecraft
  reserved-cores: 1
  
  # Environment Detection & Platform Support
  environment:
    # Auto-detect hosting environment (Pterodactyl, Docker, shared hosting, etc.)
    # Set to false to disable auto-detection and use manual settings
    auto-detect: true
    
    # Platform-specific overrides (only used if auto-detect is false)
    platform: "auto"  # Options: auto, pterodactyl, docker, shared, vps
    
    # Safety features for restricted environments
    strict-limits: true     # Enforce conservative limits in containerized/shared environments
    respect-container-limits: true  # Honor Docker/container memory/CPU limits
    
    # Environment-specific settings
    pterodactyl:
      # Conservative settings for Pterodactyl Panel compatibility
      max-cores-percentage: 50  # Use at most 50% of available cores
      disable-web-interface: true
      use-file-mode: true
      
    docker:
      # Docker container settings
      max-cores-percentage: 70  # Use at most 70% of available cores
      respect-cgroup-limits: true
      monitor-container-stats: true
      
    shared-hosting:
      # Very conservative settings for shared hosting
      max-cores: 1
      max-memory-mb: 512
      disable-ports: true
      minimal-logging: true

allocation:
  # Mode: dynamic, tiered, percentage
  mode: "dynamic"
  
  # Dynamic mode settings
  dynamic:
    cores-per-player: 0.5
    min-cores-for-minecraft: 1
    max-cores-for-fah: 7
  
  # Tiered mode settings  
  tiered:
    - players: 0
      fah-cores: 7
    - players: 1-3
      fah-cores: 5
    - players: 4-7
      fah-cores: 3
    - players: 8-12
      fah-cores: 1
    - players: 13+
      fah-cores: 0

monitoring:
  # Check interval (seconds)
  check-interval: 30
  # How often the FAH status poller runs (ticks)
  status-refresh-interval: 200
  
  # Grace period (seconds)
  grace-period: 60
  
  # TPS monitoring
  tps-monitoring: true
  min-tps: 18.0
  
  log-watchdog:
    # Time (seconds) without new FAH log entries before alerting admins
    stall-threshold-seconds: 180

  admin-alerts:
    # Send chat messages to admins when FAH changes state
    broadcast-messages: true
    # Additionally send actionbar notifications (may require Paper/Spigot API)
    actionbar-enabled: false

  structured-logging:
    # Emit JSON-formatted status updates to the console/logs
    enabled: false
  
statistics:
  # Track statistics
  enabled: true
  
  # Show on join
  show-on-join: true
  
  # Broadcast milestones
  broadcast-milestones: true

# Auto-update FAH client
auto-update: true

# Debug logging (shows FAH output and detailed status)
debug: true

# =============================================================================
# ENHANCEMENT FEATURES
# =============================================================================

# Rewards System - Give players rewards based on their contribution
rewards:
  enabled: true
  
  # Time-based rewards (hours of contribution)
  time-based:
    bronze:
      hours: 1
      name: "Bronze Contributor"
      commands:
        - "give {player} diamond 5"
      message: "&a&lREWARD! &7You've earned &eBronze Contributor &7status! (+5 diamonds)"
    
    silver:
      hours: 10
      name: "Silver Contributor"
      commands:
        - "give {player} diamond 10"
        - "give {player} emerald 5"
      message: "&a&lREWARD! &7You've earned &eSilver Contributor &7status! (+10 diamonds, +5 emeralds)"
    
    gold:
      hours: 50
      name: "Gold Contributor"
      commands:
        - "give {player} diamond 20"
        - "give {player} emerald 10"
        - "give {player} netherite_ingot 1"
      message: "&a&lREWARD! &7You've earned &eGold Contributor &7status! (+20 diamonds, +10 emeralds, +1 netherite)"
  
  # Points-based rewards
  points-based:
    milestone_1000:
      points: 1000
      name: "1K Points"
      commands:
        - "give {player} diamond 3"
      message: "&a&lMILESTONE! &7You've earned &e1,000 points &7for medical research! (+3 diamonds)"
    
    milestone_10000:
      points: 10000
      name: "10K Points"
      commands:
        - "give {player} diamond 15"
        - "give {player} emerald 5"
      message: "&a&lMILESTONE! &7You've earned &e10,000 points &7for medical research! (+15 diamonds, +5 emeralds)"
    
    milestone_100000:
      points: 100000
      name: "100K Points"
      commands:
        - "give {player} netherite_ingot 3"
      message: "&a&lMILESTONE! &7You've earned &e100,000 points &7for medical research! (+3 netherite ingots)"
  
  # Work unit completion rewards
  workunit-based:
    first_unit:
      units: 1
      name: "First Work Unit"
      commands:
        - "give {player} diamond 2"
      message: "&a&lFIRST CONTRIBUTION! &7You've completed your first work unit! (+2 diamonds)"
    
    ten_units:
      units: 10
      name: "10 Work Units"
      commands:
        - "give {player} diamond 5"
      message: "&a&lMILESTONE! &7You've completed &e10 work units! &7(+5 diamonds)"
    
    hundred_units:
      units: 100
      name: "100 Work Units"
      commands:
        - "give {player} diamond 20"
        - "give {player} netherite_ingot 2"
      message: "&a&lMILESTONE! &7You've completed &e100 work units! &7(+20 diamonds, +2 netherite)"

# Leaderboard System
leaderboard:
  enabled: true
  
  # Auto-broadcast leaderboard
  auto-broadcast:
    enabled: true
    interval-hours: 6
    type: "points"  # points, time, workunits, efficiency
    limit: 10

# Advanced Scheduling - Fold during specific hours
scheduling:
  enabled: false
  
  # Off-peak hours (when to use MORE resources)
  off-peak-start: "22:00"  # 10 PM
  off-peak-end: "06:00"    # 6 AM
  
  # Days to apply schedule (MONDAY, TUESDAY, etc.)
  active-days:
    - MONDAY
    - TUESDAY
    - WEDNESDAY
    - THURSDAY
    - FRIDAY
    - SATURDAY
    - SUNDAY
  
  # Core allocation during different times
  cores-off-peak: 4  # Use more cores during off-peak
  cores-peak: 1      # Use fewer cores during peak hours

# Health Monitoring & Auto-Recovery
health-monitoring:
  enabled: true
  
  # How often to check health (seconds)
  check-interval-seconds: 60
  
  # Automatic recovery if problems detected
  auto-recovery: true
  
  # Number of failed checks before attempting recovery
  recovery-threshold: 3
  
  # Maximum recovery attempts before giving up
  max-recovery-attempts: 3
  
  # Time (seconds) without activity before considering "stalled"
  stalled-threshold-seconds: 300

# Performance Tracking
performance-tracking:
  enabled: true
  
  # Track CPU usage (requires system permissions)
  track-cpu: true
  
  # Track memory usage
  track-memory: true
  
  # Auto-generate performance reports
  auto-report:
    enabled: false
    interval-hours: 24

# Data storage (managed automatically)
data:
  contributions: {}
  leaderboard: {}