name: Build Plugin

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean shadowJar --no-daemon
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FAHResourceDonor-Plugin
        path: build/libs/*.jar
        retention-days: 30
        
    - name: Display build info
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 JAR file created:"
        ls -lh build/libs/*.jar
